# Generated by Django 5.1.5 on 2025-02-04 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0005_course_discount_alter_assignment_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='general_discount',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
