# Generated by Django 5.1.5 on 2025-02-04 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0006_course_general_discount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='general_discount',
            new_name='general_price',
        ),
    ]
