# Generated by Django 5.1.5 on 2025-02-04 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0007_rename_general_discount_course_general_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='general_price',
        ),
    ]
