# Generated by Django 5.1.5 on 2025-02-04 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0009_generalcourseprice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generalcourseprice',
            old_name='general_price',
            new_name='price',
        ),
    ]
