# Generated by Django 5.1.5 on 2025-02-04 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0010_rename_general_price_generalcourseprice_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
