# Generated by Django 5.1.5 on 2025-02-04 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0011_course_old_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='admin_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
