# Generated by Django 5.1.5 on 2025-02-08 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0014_alter_cartitem_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='course_app.cart'),
        ),
        migrations.AlterField(
            model_name='course',
            name='author',
            field=models.ManyToManyField(related_name='teacher_courses', to='course_app.teacher'),
        ),
        migrations.AlterField(
            model_name='favoriteitem',
            name='favorite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_items', to='course_app.favorite'),
        ),
        migrations.AlterField(
            model_name='teacherrating',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_ratings', to='course_app.teacher'),
        ),
    ]
